import random

def recommend_music(mood: str) -> str:
    music = {
        "happy": ["Pop music", 
                  "Upbeat electronic music"
                  "Walking on a Dream",
                  "Good as Hell",
                  "The Nights",
                  "Put Your Records On",
                  "Can’t Stop the Feeling",
                  "September",
                  "Love Me Again"],
        "sad": ["Soft piano music", 
                "Lyrical ballads",
                "The Night We Met",
                "Fix You",
                "I Will Follow You into the Dark",
                "Lost Cause",
                "When We Were Young",
                "Wake Me Up When September Ends",
                "To Build a Home",
                "The Scientist",
                "Hard Sometimes"],
        "stressed": ["Nature sounds", 
                     "Calm instrumental music",
                     "Weightless",
                     "Sunset Lover",
                     "Holocene",
                     "Clair de Lune",
                     "River Flows in You",
                     "Bloom",
                     "Opus 23",
                     "Night Owl",
                     "Breathe Me",
                     "Saturn"],
        "bored": ["Jazz", 
                  "Rock music",
                  "Dog Days Are Over",
                  "Take a Walk",
                  "Paper Planes",
                  "Houdini",
                  "Are You Bored Yet?",
                  "Go Your Own Way",
                  "Dance, Dance",
                  "Young Folks",
                  "Shut Up and Dance",
                  "HandClap"]
    }
    return random.choice(music.get(mood.lower(), ["Explore a new music genre!"]))