name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]  # 测试两个不同的 Python 版本

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
        pipenv install -e .
    
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV  


    - name: Debug environment
      run: |
        pipenv run pip list | grep pytest  
        pipenv run python -c "import sys; print(sys.executable)"  

    - name: Run tests
      run: pipenv run python -m pytest
      